### ISSUE TITLE
Why do we need Framework.js.Can you do something more meaningful?

### ISSUE THREAD

**Issue by blurHY** [Plasnerd/Framework.js#89]
I use Vue+Bootstrap and a monkeypatch for zeronet.
You have time to develop Framework.js,but why not to do something more useful for zeronet and the users.
Stop making useless comment system etc.

**Comment by DaniellMesquita** [comment]
Useless comment system? ZeroNet needs a comment system.

About Vue, it isn't easy for newbie users.
I'd setup Vue with Vuetify, and some components simply didn't worked, and the same happened with Angular+Angular Material.

"Why do we need Framework.js"

It's already explained lots of times:

* Simply click on "Create your own zite", and you will be redirected to your brand new project with instructions for how to modify it
* Detect if its on ZeroNet or on Clearnet (the begin of UltraApps' hybrid app concept)
* Automatic dark theme
* API to clone own zite or other zites (like Git Center works with its repos - that API will be useful for blogs, forums, and other CMS on ZN)
* Built-in Bootstrap, Material Design, Roboto/ZeroNet font, Material Icons
* Basic things that are need from a web framework

Plus the fact that FrameworkJS is the only framework that beyond of being newbie-friendly, it is dedicated to ZeroNet and its features, and also is proudly born on ZeroNet.

**Comment by blurHY** [comment]
Oh,yeah,vue isn't easy.
And newbies don't know how to create a comment system.
You want to build a newbie-friendly site building framework.

**Comment by DaniellMesquita** [comment]
@blurHY
> And newbies don't know how to create a comment system.

What did you mean?
